create table public."Location" (
	"Id" INT,
	"City" TEXT,
	"Country" TEXT
);
insert into public."Location" ("Id", "City", "Country") values (1, 'Lhokkruet', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (2, 'Vallentuna', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (3, 'Serh', 'China');
insert into public."Location" ("Id", "City", "Country") values (4, 'Duiwelskloof', 'South Africa');
insert into public."Location" ("Id", "City", "Country") values (5, 'Andres Bonifacio', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (6, 'Huacrachuco', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (7, 'Dve Mogili', 'Bulgaria');
insert into public."Location" ("Id", "City", "Country") values (8, 'Pisões', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (9, 'Maralik', 'Armenia');
insert into public."Location" ("Id", "City", "Country") values (10, 'Shatian', 'China');
insert into public."Location" ("Id", "City", "Country") values (11, 'New Haven', 'United States');
insert into public."Location" ("Id", "City", "Country") values (12, 'Galesong', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (13, 'Jubao', 'China');
insert into public."Location" ("Id", "City", "Country") values (14, 'Markovo', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (15, 'Dzięgielów', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (16, 'Granja', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (17, 'L''Assomption', 'Canada');
insert into public."Location" ("Id", "City", "Country") values (18, 'Chicago', 'United States');
insert into public."Location" ("Id", "City", "Country") values (19, 'Dana', 'China');
insert into public."Location" ("Id", "City", "Country") values (20, 'Khadzhalmakhi', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (21, 'Tumbagaan', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (22, 'Revda', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (23, 'Wakefield', 'Jamaica');
insert into public."Location" ("Id", "City", "Country") values (24, 'Vienne', 'France');
insert into public."Location" ("Id", "City", "Country") values (25, 'Buffalo', 'United States');
insert into public."Location" ("Id", "City", "Country") values (26, 'Haninge', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (27, 'Birmingham', 'United States');
insert into public."Location" ("Id", "City", "Country") values (28, 'Santiago de las Vegas', 'Cuba');
insert into public."Location" ("Id", "City", "Country") values (29, 'Mantar', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (30, 'Babatngon', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (31, 'Quận Sáu', 'Vietnam');
insert into public."Location" ("Id", "City", "Country") values (32, 'Huaidao', 'China');
insert into public."Location" ("Id", "City", "Country") values (33, 'Beutong Ateuh', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (34, 'Yiliu', 'China');
insert into public."Location" ("Id", "City", "Country") values (35, 'Jbaïl', 'Lebanon');
insert into public."Location" ("Id", "City", "Country") values (36, 'Saint-Quentin-en-Yvelines', 'France');
insert into public."Location" ("Id", "City", "Country") values (37, 'Psará', 'Greece');
insert into public."Location" ("Id", "City", "Country") values (38, 'Tomakivka', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (39, 'Halimpu', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (40, 'Yaogu', 'China');
insert into public."Location" ("Id", "City", "Country") values (41, 'Wasogolo', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (42, 'Pohang', 'South Korea');
insert into public."Location" ("Id", "City", "Country") values (43, 'Yuntan', 'China');
insert into public."Location" ("Id", "City", "Country") values (44, 'Baiyang', 'China');
insert into public."Location" ("Id", "City", "Country") values (45, 'Senggapi', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (46, 'Karangwaru', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (47, 'Balakliya', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (48, 'Jianshan', 'China');
insert into public."Location" ("Id", "City", "Country") values (49, 'Igang', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (50, 'KwaMbonambi', 'South Africa');
insert into public."Location" ("Id", "City", "Country") values (51, 'Neftçala', 'Azerbaijan');
insert into public."Location" ("Id", "City", "Country") values (52, 'Xinan', 'China');
insert into public."Location" ("Id", "City", "Country") values (53, 'Kuching', 'Malaysia');
insert into public."Location" ("Id", "City", "Country") values (54, 'Sanya', 'China');
insert into public."Location" ("Id", "City", "Country") values (55, 'Babakan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (56, 'Dananyu', 'China');
insert into public."Location" ("Id", "City", "Country") values (57, 'Oyama', 'Japan');
insert into public."Location" ("Id", "City", "Country") values (58, 'Dingbu', 'China');
insert into public."Location" ("Id", "City", "Country") values (59, 'Culasian', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (60, 'Tall Salḩab', 'Syria');
insert into public."Location" ("Id", "City", "Country") values (61, 'Calvário', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (62, 'Zelenogradsk', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (63, 'Timezgana', 'Morocco');
insert into public."Location" ("Id", "City", "Country") values (64, 'Tartouss', 'Syria');
insert into public."Location" ("Id", "City", "Country") values (65, 'Sukorejo', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (66, 'Uubulan', 'Mongolia');
insert into public."Location" ("Id", "City", "Country") values (67, 'Gyigang', 'China');
insert into public."Location" ("Id", "City", "Country") values (68, 'Saint-Maixent-l''École', 'France');
insert into public."Location" ("Id", "City", "Country") values (69, 'Klemunan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (70, 'Przyborów', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (71, 'Cankova', 'Slovenia');
insert into public."Location" ("Id", "City", "Country") values (72, 'Ayna', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (73, 'Kim Sơn', 'Vietnam');
insert into public."Location" ("Id", "City", "Country") values (74, 'Knežica', 'Bosnia and Herzegovina');
insert into public."Location" ("Id", "City", "Country") values (75, 'Matoupu', 'China');
insert into public."Location" ("Id", "City", "Country") values (76, 'Tijão', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (77, 'Maomiaoji', 'China');
insert into public."Location" ("Id", "City", "Country") values (78, 'Leku', 'Ethiopia');
insert into public."Location" ("Id", "City", "Country") values (79, 'Kedungasem', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (80, 'Katoúna', 'Greece');
insert into public."Location" ("Id", "City", "Country") values (81, 'Polkowice', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (82, 'Yāsūf', 'Palestinian Territory');
insert into public."Location" ("Id", "City", "Country") values (83, 'Tapilon', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (84, 'Le Cannet', 'France');
insert into public."Location" ("Id", "City", "Country") values (85, 'Fuzhou', 'China');
insert into public."Location" ("Id", "City", "Country") values (86, 'Lubniewice', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (87, 'Driyorejo', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (88, 'Shensuo', 'China');
insert into public."Location" ("Id", "City", "Country") values (89, 'Tengger', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (90, 'Mandapajaya', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (91, 'Hukou', 'China');
insert into public."Location" ("Id", "City", "Country") values (92, 'San Francisco de Coray', 'Honduras');
insert into public."Location" ("Id", "City", "Country") values (93, 'Liperi', 'Finland');
insert into public."Location" ("Id", "City", "Country") values (94, 'Beirut', 'Lebanon');
insert into public."Location" ("Id", "City", "Country") values (95, 'Payabon', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (96, 'Zhudian', 'China');
insert into public."Location" ("Id", "City", "Country") values (97, 'Talovyy', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (98, 'Bartolomé Masó', 'Cuba');
insert into public."Location" ("Id", "City", "Country") values (99, 'Şanā’', 'Yemen');
insert into public."Location" ("Id", "City", "Country") values (100, 'Grangwav', 'Haiti');
insert into public."Location" ("Id", "City", "Country") values (101, 'Baisha', 'China');
insert into public."Location" ("Id", "City", "Country") values (102, 'Listvyanka', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (103, 'Kyperoúnta', 'Cyprus');
insert into public."Location" ("Id", "City", "Country") values (104, 'Cipaku', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (105, 'Tourcoing', 'France');
insert into public."Location" ("Id", "City", "Country") values (106, 'Waitakere', 'New Zealand');
insert into public."Location" ("Id", "City", "Country") values (107, 'Ilinden', 'Macedonia');
insert into public."Location" ("Id", "City", "Country") values (108, 'Albion', 'Mauritius');
insert into public."Location" ("Id", "City", "Country") values (109, 'Fandriana', 'Madagascar');
insert into public."Location" ("Id", "City", "Country") values (110, 'Sida', 'Thailand');
insert into public."Location" ("Id", "City", "Country") values (111, 'Ko Samui', 'Thailand');
insert into public."Location" ("Id", "City", "Country") values (112, 'Rikitea', 'French Polynesia');
insert into public."Location" ("Id", "City", "Country") values (113, 'Busuanga', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (114, 'Zhexiao', 'China');
insert into public."Location" ("Id", "City", "Country") values (115, 'Chahār Burj', 'Afghanistan');
insert into public."Location" ("Id", "City", "Country") values (116, 'Kåge', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (117, 'Makale', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (118, 'Banyutengah', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (119, 'Patrol', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (120, 'Kafr ash Shaykh', 'Egypt');
insert into public."Location" ("Id", "City", "Country") values (121, 'Maji', 'China');
insert into public."Location" ("Id", "City", "Country") values (122, 'Turba', 'Estonia');
insert into public."Location" ("Id", "City", "Country") values (123, 'Wenshang', 'China');
insert into public."Location" ("Id", "City", "Country") values (124, 'Marne-la-Vallée', 'France');
insert into public."Location" ("Id", "City", "Country") values (125, 'Dalam', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (126, 'Yangying', 'China');
insert into public."Location" ("Id", "City", "Country") values (127, 'Longhua', 'China');
insert into public."Location" ("Id", "City", "Country") values (128, 'Novo-Peredelkino', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (129, 'Nanga Eboko', 'Cameroon');
insert into public."Location" ("Id", "City", "Country") values (130, 'Shādegān', 'Iran');
insert into public."Location" ("Id", "City", "Country") values (131, 'Yambol', 'Bulgaria');
insert into public."Location" ("Id", "City", "Country") values (132, 'Fayzabad', 'Afghanistan');
insert into public."Location" ("Id", "City", "Country") values (133, 'Loureiro', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (134, 'Xinfang', 'China');
insert into public."Location" ("Id", "City", "Country") values (135, 'Berovo', 'Macedonia');
insert into public."Location" ("Id", "City", "Country") values (136, 'Kabacan', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (137, 'Koryukivka', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (138, 'Watulumbung', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (139, 'Évreux', 'France');
insert into public."Location" ("Id", "City", "Country") values (140, 'Lubrza', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (141, 'Jales', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (142, 'Sanjiang', 'China');
insert into public."Location" ("Id", "City", "Country") values (143, 'Hidalgo', 'Mexico');
insert into public."Location" ("Id", "City", "Country") values (144, 'Massenya', 'Chad');
insert into public."Location" ("Id", "City", "Country") values (145, 'Ejidal', 'Mexico');
insert into public."Location" ("Id", "City", "Country") values (146, 'Morgados', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (147, 'Sundsvall', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (148, 'Banjar Wates Tengah', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (149, 'Ambam', 'Cameroon');
insert into public."Location" ("Id", "City", "Country") values (150, 'Rungis', 'France');
insert into public."Location" ("Id", "City", "Country") values (151, 'Fuli', 'China');
insert into public."Location" ("Id", "City", "Country") values (152, 'Semibratovo', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (153, 'Lyon', 'France');
insert into public."Location" ("Id", "City", "Country") values (154, 'Hässelby', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (155, 'Mae Lao', 'Thailand');
insert into public."Location" ("Id", "City", "Country") values (156, 'Clonskeagh', 'Ireland');
insert into public."Location" ("Id", "City", "Country") values (157, 'Cibeureum', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (158, 'Al Wuday‘', 'Yemen');
insert into public."Location" ("Id", "City", "Country") values (159, 'Batasan Bata', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (160, 'Alfta', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (161, 'Bayawan', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (162, 'Kuala Lumpur', 'Malaysia');
insert into public."Location" ("Id", "City", "Country") values (163, 'Youfang', 'China');
insert into public."Location" ("Id", "City", "Country") values (164, 'Qārah', 'Syria');
insert into public."Location" ("Id", "City", "Country") values (165, 'San Pedro Pinula', 'Guatemala');
insert into public."Location" ("Id", "City", "Country") values (166, 'Bairan', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (167, 'Aurora', 'United States');
insert into public."Location" ("Id", "City", "Country") values (168, 'Borovskoy', 'Kazakhstan');
insert into public."Location" ("Id", "City", "Country") values (169, 'Thị Trấn Sìn Hồ', 'Vietnam');
insert into public."Location" ("Id", "City", "Country") values (170, 'Changxing', 'China');
insert into public."Location" ("Id", "City", "Country") values (171, 'Luchingu', 'Tanzania');
insert into public."Location" ("Id", "City", "Country") values (172, 'Zhangdiyingzi', 'China');
insert into public."Location" ("Id", "City", "Country") values (173, 'Livramento', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (174, 'Jixiang', 'China');
insert into public."Location" ("Id", "City", "Country") values (175, 'North Bay', 'Canada');
insert into public."Location" ("Id", "City", "Country") values (176, 'Matarraque', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (177, 'Koba', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (178, 'Bouca', 'Central African Republic');
insert into public."Location" ("Id", "City", "Country") values (179, 'Bulls', 'New Zealand');
insert into public."Location" ("Id", "City", "Country") values (180, 'Luhačovice', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (181, 'Curahuasi', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (182, 'Machinda', 'Equatorial Guinea');
insert into public."Location" ("Id", "City", "Country") values (183, 'Hino', 'Japan');
insert into public."Location" ("Id", "City", "Country") values (184, 'Khakhea', 'Botswana');
insert into public."Location" ("Id", "City", "Country") values (185, 'Bafatá', 'Guinea-Bissau');
insert into public."Location" ("Id", "City", "Country") values (186, 'Heping', 'China');
insert into public."Location" ("Id", "City", "Country") values (187, 'Heliconia', 'Colombia');
insert into public."Location" ("Id", "City", "Country") values (188, 'Petaling Jaya', 'Malaysia');
insert into public."Location" ("Id", "City", "Country") values (189, 'Heitan', 'China');
insert into public."Location" ("Id", "City", "Country") values (190, 'Bintuni', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (191, 'Murcia', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (192, 'Värnamo', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (193, 'Manggu', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (194, 'Huibu', 'China');
insert into public."Location" ("Id", "City", "Country") values (195, 'Bahía de Caráquez', 'Ecuador');
insert into public."Location" ("Id", "City", "Country") values (196, 'Campor', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (197, 'Cikeusal', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (198, 'Geta', 'Aland Islands');
insert into public."Location" ("Id", "City", "Country") values (199, 'Abadiânia', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (200, 'Morazán', 'Guatemala');
insert into public."Location" ("Id", "City", "Country") values (201, 'Nkpor', 'Nigeria');
insert into public."Location" ("Id", "City", "Country") values (202, 'Mozdok', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (203, 'Corpus Christi', 'United States');
insert into public."Location" ("Id", "City", "Country") values (204, 'Hrob', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (205, 'Aş Şanamayn', 'Syria');
insert into public."Location" ("Id", "City", "Country") values (206, 'Zungeru', 'Nigeria');
insert into public."Location" ("Id", "City", "Country") values (207, 'Qunsheng', 'China');
insert into public."Location" ("Id", "City", "Country") values (208, 'Ratenggoji', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (209, 'Corona', 'United States');
insert into public."Location" ("Id", "City", "Country") values (210, 'Can-asujan', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (211, 'Wudangshan', 'China');
insert into public."Location" ("Id", "City", "Country") values (212, 'Heret', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (213, 'Palon', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (214, 'Valença', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (215, 'Shuiyuan', 'China');
insert into public."Location" ("Id", "City", "Country") values (216, 'Guéret', 'France');
insert into public."Location" ("Id", "City", "Country") values (217, 'Shuiyuan', 'China');
insert into public."Location" ("Id", "City", "Country") values (218, 'Monte do Outeiro', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (219, 'Zykovo', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (220, 'Ar Rumaythīyah', 'Kuwait');
insert into public."Location" ("Id", "City", "Country") values (221, 'Ozubulu', 'Nigeria');
insert into public."Location" ("Id", "City", "Country") values (222, 'Guangping', 'China');
insert into public."Location" ("Id", "City", "Country") values (223, 'Dumlan', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (224, 'Zhangfeng', 'China');
insert into public."Location" ("Id", "City", "Country") values (225, 'Cabatuan', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (226, 'Shiraoi', 'Japan');
insert into public."Location" ("Id", "City", "Country") values (227, 'Borovskoy', 'Kazakhstan');
insert into public."Location" ("Id", "City", "Country") values (228, 'Sirib', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (229, 'Manalongon', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (230, 'Saint-Avertin', 'France');
insert into public."Location" ("Id", "City", "Country") values (231, 'Stamford', 'United States');
insert into public."Location" ("Id", "City", "Country") values (232, 'Dongling', 'China');
insert into public."Location" ("Id", "City", "Country") values (233, 'Bishan', 'China');
insert into public."Location" ("Id", "City", "Country") values (234, 'San Ignacio', 'Honduras');
insert into public."Location" ("Id", "City", "Country") values (235, 'Rego', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (236, 'Los Dos Caminos', 'Venezuela');
insert into public."Location" ("Id", "City", "Country") values (237, 'Kalianyar Selatan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (238, 'Chambishi', 'Zambia');
insert into public."Location" ("Id", "City", "Country") values (239, 'Maiwal', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (240, 'Kallithéa', 'Greece');
insert into public."Location" ("Id", "City", "Country") values (241, 'Stara Kornica', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (242, 'Polomolok', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (243, 'Zhushan', 'China');
insert into public."Location" ("Id", "City", "Country") values (244, 'Lazaro Cardenas', 'Mexico');
insert into public."Location" ("Id", "City", "Country") values (245, 'Wola Sernicka', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (246, 'Zhujiang', 'China');
insert into public."Location" ("Id", "City", "Country") values (247, 'Yanghou', 'China');
insert into public."Location" ("Id", "City", "Country") values (248, 'São Sebastião do Caí', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (249, 'Santo Tomas', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (250, 'Noginsk-9', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (251, 'Orlando', 'United States');
insert into public."Location" ("Id", "City", "Country") values (252, 'Créteil', 'France');
insert into public."Location" ("Id", "City", "Country") values (253, 'Solnice', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (254, 'Andramasina', 'Madagascar');
insert into public."Location" ("Id", "City", "Country") values (255, 'Alvaro Obregon', 'Mexico');
insert into public."Location" ("Id", "City", "Country") values (256, 'Šenčur', 'Slovenia');
insert into public."Location" ("Id", "City", "Country") values (257, 'Raemude', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (258, 'Ulyanovsk', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (259, 'Ceper', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (260, 'Abilay', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (261, 'Rio Claro', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (262, 'Mutengene', 'Cameroon');
insert into public."Location" ("Id", "City", "Country") values (263, 'Darungan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (264, 'Bayt Wazan', 'Palestinian Territory');
insert into public."Location" ("Id", "City", "Country") values (265, 'Mwene-Ditu', 'Democratic Republic of the Congo');
insert into public."Location" ("Id", "City", "Country") values (266, 'Fordon', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (267, 'Tignapalan', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (268, 'Tršić', 'Serbia');
insert into public."Location" ("Id", "City", "Country") values (269, 'Confey', 'Ireland');
insert into public."Location" ("Id", "City", "Country") values (270, 'Xike', 'China');
insert into public."Location" ("Id", "City", "Country") values (271, 'Paris 07', 'France');
insert into public."Location" ("Id", "City", "Country") values (272, 'Borovlyany', 'Belarus');
insert into public."Location" ("Id", "City", "Country") values (273, 'Nato', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (274, 'Cikujang', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (275, 'Vaiusu', 'Samoa');
insert into public."Location" ("Id", "City", "Country") values (276, 'Mar del Plata', 'Argentina');
insert into public."Location" ("Id", "City", "Country") values (277, 'Raciąż', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (278, 'Andovoranto', 'Madagascar');
insert into public."Location" ("Id", "City", "Country") values (279, 'Arendal', 'Norway');
insert into public."Location" ("Id", "City", "Country") values (280, 'Adh Dhayd', 'United Arab Emirates');
insert into public."Location" ("Id", "City", "Country") values (281, 'Caohe', 'China');
insert into public."Location" ("Id", "City", "Country") values (282, 'Takahata', 'Japan');
insert into public."Location" ("Id", "City", "Country") values (283, 'Komsomol’skiy', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (284, 'Dole', 'France');
insert into public."Location" ("Id", "City", "Country") values (285, 'Khamis Mushait', 'Saudi Arabia');
insert into public."Location" ("Id", "City", "Country") values (286, 'Tebon', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (287, 'Kandhkot', 'Pakistan');
insert into public."Location" ("Id", "City", "Country") values (288, 'Tílisos', 'Greece');
insert into public."Location" ("Id", "City", "Country") values (289, 'Lubin', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (290, 'Chimbas', 'Argentina');
insert into public."Location" ("Id", "City", "Country") values (291, 'Maganha', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (292, 'Penedo', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (293, 'Bent Jbaïl', 'Lebanon');
insert into public."Location" ("Id", "City", "Country") values (294, 'San Pablo', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (295, 'Francisco Villa', 'Mexico');
insert into public."Location" ("Id", "City", "Country") values (296, 'Nerekhta', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (297, 'Lidköping', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (298, 'Rízoma', 'Greece');
insert into public."Location" ("Id", "City", "Country") values (299, 'Mongar', 'Bhutan');
insert into public."Location" ("Id", "City", "Country") values (300, 'Alajuela', 'Costa Rica');
insert into public."Location" ("Id", "City", "Country") values (301, 'Tucuruí', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (302, 'Chauk', 'Myanmar');
insert into public."Location" ("Id", "City", "Country") values (303, 'Jendouba', 'Tunisia');
insert into public."Location" ("Id", "City", "Country") values (304, 'Säffle', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (305, 'Mwaya', 'Tanzania');
insert into public."Location" ("Id", "City", "Country") values (306, 'Heping', 'China');
insert into public."Location" ("Id", "City", "Country") values (307, 'Černožice', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (308, 'Kafr Miṣr', 'Israel');
insert into public."Location" ("Id", "City", "Country") values (309, 'Samoš', 'Serbia');
insert into public."Location" ("Id", "City", "Country") values (310, 'Sawahrandu', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (311, 'La Guadalupe', 'Mexico');
insert into public."Location" ("Id", "City", "Country") values (312, 'Tunoshna', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (313, 'Nordeste', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (314, 'Zelenodolsk', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (315, 'Cambrai', 'France');
insert into public."Location" ("Id", "City", "Country") values (316, 'Yantak', 'China');
insert into public."Location" ("Id", "City", "Country") values (317, 'Ust’-Labinsk', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (318, 'Rymanów', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (319, 'Quba', 'Azerbaijan');
insert into public."Location" ("Id", "City", "Country") values (320, 'Moshenskoye', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (321, 'Honglu', 'China');
insert into public."Location" ("Id", "City", "Country") values (322, 'Évry', 'France');
insert into public."Location" ("Id", "City", "Country") values (323, 'Svetlyy', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (324, 'Ar Riqāb', 'Tunisia');
insert into public."Location" ("Id", "City", "Country") values (325, 'Pugeran', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (326, 'Babat', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (327, 'Montreuil', 'France');
insert into public."Location" ("Id", "City", "Country") values (328, 'Karangsono', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (329, 'Stary Sącz', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (330, 'Chinhoyi', 'Zimbabwe');
insert into public."Location" ("Id", "City", "Country") values (331, 'Lyon', 'France');
insert into public."Location" ("Id", "City", "Country") values (332, 'Guarabira', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (333, 'Wangi', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (334, 'Bulog', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (335, 'Huangjinjing', 'China');
insert into public."Location" ("Id", "City", "Country") values (336, 'Kudang', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (337, 'Ulanov', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (338, 'Ożarowice', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (339, 'Wolowona', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (340, 'Sukadana', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (341, 'Koupéla', 'Burkina Faso');
insert into public."Location" ("Id", "City", "Country") values (342, 'Xiawa', 'China');
insert into public."Location" ("Id", "City", "Country") values (343, 'Río Segundo', 'Argentina');
insert into public."Location" ("Id", "City", "Country") values (344, 'Pavino', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (345, 'Guruafin', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (346, 'Béziers', 'France');
insert into public."Location" ("Id", "City", "Country") values (347, 'Kizhinga', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (348, 'Kardamás', 'Greece');
insert into public."Location" ("Id", "City", "Country") values (349, 'Tangwei', 'China');
insert into public."Location" ("Id", "City", "Country") values (350, 'Huacrachuco', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (351, 'Salamnunggal', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (352, 'Obukhiv', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (353, 'Toulon', 'France');
insert into public."Location" ("Id", "City", "Country") values (354, 'Krajandadapmulyo', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (355, 'Shinao', 'China');
insert into public."Location" ("Id", "City", "Country") values (356, 'Dahuaishu', 'China');
insert into public."Location" ("Id", "City", "Country") values (357, 'Khanabad', 'Afghanistan');
insert into public."Location" ("Id", "City", "Country") values (358, 'Checacupe', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (359, 'Ust’-Katav', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (360, 'Ejidal', 'Mexico');
insert into public."Location" ("Id", "City", "Country") values (361, 'Malusay', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (362, 'Wawer', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (363, 'Fundão', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (364, 'Torino', 'Italy');
insert into public."Location" ("Id", "City", "Country") values (365, 'Karema', 'Tanzania');
insert into public."Location" ("Id", "City", "Country") values (366, 'Soavinandriana', 'Madagascar');
insert into public."Location" ("Id", "City", "Country") values (367, 'Wujia', 'China');
insert into public."Location" ("Id", "City", "Country") values (368, 'Bardo', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (369, 'Tây Đằng', 'Vietnam');
insert into public."Location" ("Id", "City", "Country") values (370, 'Horodyshche', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (371, 'Shaxi', 'China');
insert into public."Location" ("Id", "City", "Country") values (372, 'Aileu', 'East Timor');
insert into public."Location" ("Id", "City", "Country") values (373, 'Beaumont', 'Canada');
insert into public."Location" ("Id", "City", "Country") values (374, 'Sidzina', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (375, 'Kasungu', 'Malawi');
insert into public."Location" ("Id", "City", "Country") values (376, 'Oklahoma City', 'United States');
insert into public."Location" ("Id", "City", "Country") values (377, 'Eirunepé', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (378, 'Rrapë', 'Albania');
insert into public."Location" ("Id", "City", "Country") values (379, 'Pincher Creek', 'Canada');
insert into public."Location" ("Id", "City", "Country") values (380, 'Saint-Jérôme', 'Canada');
insert into public."Location" ("Id", "City", "Country") values (381, 'Sidomulyo', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (382, 'Stockholm', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (383, 'Działoszyce', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (384, 'Beigou', 'China');
insert into public."Location" ("Id", "City", "Country") values (385, 'Dajt', 'Albania');
insert into public."Location" ("Id", "City", "Country") values (386, 'Cijayana', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (387, 'Lubao', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (388, 'Manola', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (389, 'Pakuwon', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (390, 'Detroit', 'United States');
insert into public."Location" ("Id", "City", "Country") values (391, 'Rostov', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (392, 'Fuxing', 'China');
insert into public."Location" ("Id", "City", "Country") values (393, 'Wisła', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (394, 'Thatta', 'Pakistan');
insert into public."Location" ("Id", "City", "Country") values (395, 'Prachin Buri', 'Thailand');
insert into public."Location" ("Id", "City", "Country") values (396, 'Qinjia', 'China');
insert into public."Location" ("Id", "City", "Country") values (397, 'Karnice', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (398, 'Xiaoguan', 'China');
insert into public."Location" ("Id", "City", "Country") values (399, 'Dingdian', 'China');
insert into public."Location" ("Id", "City", "Country") values (400, 'San Diego', 'Costa Rica');
insert into public."Location" ("Id", "City", "Country") values (401, 'Roanoke', 'United States');
insert into public."Location" ("Id", "City", "Country") values (402, 'Dusun Desa Bunter', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (403, 'Lipka', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (404, 'Huagu', 'China');
insert into public."Location" ("Id", "City", "Country") values (405, 'Qārah', 'Syria');
insert into public."Location" ("Id", "City", "Country") values (406, 'Rychnov nad Kněžnou', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (407, 'Jiazhuang', 'China');
insert into public."Location" ("Id", "City", "Country") values (408, 'Ore', 'Nigeria');
insert into public."Location" ("Id", "City", "Country") values (409, 'Panjerrejo', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (410, 'San Andres', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (411, 'Lembung Tengah', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (412, 'Hulu', 'China');
insert into public."Location" ("Id", "City", "Country") values (413, 'Guamal', 'Colombia');
insert into public."Location" ("Id", "City", "Country") values (414, 'Évry', 'France');
insert into public."Location" ("Id", "City", "Country") values (415, 'Nanjie', 'China');
insert into public."Location" ("Id", "City", "Country") values (416, 'Lichengdao', 'China');
insert into public."Location" ("Id", "City", "Country") values (417, 'Palaífyto', 'Greece');
insert into public."Location" ("Id", "City", "Country") values (418, 'Vose’', 'Tajikistan');
insert into public."Location" ("Id", "City", "Country") values (419, 'Mont-Laurier', 'Canada');
insert into public."Location" ("Id", "City", "Country") values (420, 'Manga', 'Burkina Faso');
insert into public."Location" ("Id", "City", "Country") values (421, 'Zheleznogorsk', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (422, 'San Nicolas', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (423, 'Jianggezhuang', 'China');
insert into public."Location" ("Id", "City", "Country") values (424, 'Diapaga', 'Burkina Faso');
insert into public."Location" ("Id", "City", "Country") values (425, 'Melaka', 'Malaysia');
insert into public."Location" ("Id", "City", "Country") values (426, 'Krasni Okny', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (427, 'Bayt Līd', 'Palestinian Territory');
insert into public."Location" ("Id", "City", "Country") values (428, 'Jiangkou', 'China');
insert into public."Location" ("Id", "City", "Country") values (429, 'Krajan Waturoyo', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (430, 'Zelenodolsk', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (431, 'Rancapanjang', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (432, 'Međa', 'Serbia');
insert into public."Location" ("Id", "City", "Country") values (433, 'Darungan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (434, 'Giemdiem', 'Vietnam');
insert into public."Location" ("Id", "City", "Country") values (435, 'Yingchun', 'China');
insert into public."Location" ("Id", "City", "Country") values (436, 'Matahuasi', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (437, 'Vila Nova Sintra', 'Cape Verde');
insert into public."Location" ("Id", "City", "Country") values (438, 'Santa Cruz', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (439, 'Gorbunki', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (440, 'Jiubao', 'China');
insert into public."Location" ("Id", "City", "Country") values (441, 'Nankou', 'China');
insert into public."Location" ("Id", "City", "Country") values (442, 'Guayabal', 'Venezuela');
insert into public."Location" ("Id", "City", "Country") values (443, 'Hejiang', 'China');
insert into public."Location" ("Id", "City", "Country") values (444, 'At Samat', 'Thailand');
insert into public."Location" ("Id", "City", "Country") values (445, 'Bandar-e Torkaman', 'Iran');
insert into public."Location" ("Id", "City", "Country") values (446, 'Lisewo', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (447, 'Üydzen', 'Mongolia');
insert into public."Location" ("Id", "City", "Country") values (448, 'Penha', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (449, 'Västerås', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (450, 'San Cristóbal', 'Venezuela');
insert into public."Location" ("Id", "City", "Country") values (451, 'Malasin', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (452, 'Wolofeo', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (453, 'Przecław', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (454, 'Kebon', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (455, 'Chadan', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (456, 'Cabeço', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (457, 'Wangdun', 'China');
insert into public."Location" ("Id", "City", "Country") values (458, 'Khūgyāṉī', 'Afghanistan');
insert into public."Location" ("Id", "City", "Country") values (459, 'Jonquière', 'Canada');
insert into public."Location" ("Id", "City", "Country") values (460, 'Krajan Tegalombo', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (461, 'Đình Lập', 'Vietnam');
insert into public."Location" ("Id", "City", "Country") values (462, 'Mugala', 'China');
insert into public."Location" ("Id", "City", "Country") values (463, 'Jiguan', 'China');
insert into public."Location" ("Id", "City", "Country") values (464, 'Santa Rita', 'Mexico');
insert into public."Location" ("Id", "City", "Country") values (465, 'Jiangchang', 'China');
insert into public."Location" ("Id", "City", "Country") values (466, 'Yaguajay', 'Cuba');
insert into public."Location" ("Id", "City", "Country") values (467, 'Hînceşti', 'Moldova');
insert into public."Location" ("Id", "City", "Country") values (468, 'Saint-Nazaire', 'France');
insert into public."Location" ("Id", "City", "Country") values (469, 'Jalālābād', 'Afghanistan');
insert into public."Location" ("Id", "City", "Country") values (470, 'Solosolo', 'Samoa');
insert into public."Location" ("Id", "City", "Country") values (471, 'Heichengzi', 'China');
insert into public."Location" ("Id", "City", "Country") values (472, 'Sarilhos Grandes', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (473, 'Wates', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (474, 'Bagadó', 'Colombia');
insert into public."Location" ("Id", "City", "Country") values (475, 'San José', 'Honduras');
insert into public."Location" ("Id", "City", "Country") values (476, 'Silvares', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (477, 'Ciyu', 'China');
insert into public."Location" ("Id", "City", "Country") values (478, 'Zaporizhzhya', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (479, 'Shazi', 'China');
insert into public."Location" ("Id", "City", "Country") values (480, 'Brloh', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (481, 'Denver', 'United States');
insert into public."Location" ("Id", "City", "Country") values (482, 'Cluain Meala', 'Ireland');
insert into public."Location" ("Id", "City", "Country") values (483, 'Ocumare de la Costa', 'Venezuela');
insert into public."Location" ("Id", "City", "Country") values (484, 'Sintra', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (485, 'Tarczyn', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (486, 'Hanzhong', 'China');
insert into public."Location" ("Id", "City", "Country") values (487, 'Seara', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (488, 'Namayingo', 'Uganda');
insert into public."Location" ("Id", "City", "Country") values (489, 'Żarki', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (490, 'Miaoyu', 'China');
insert into public."Location" ("Id", "City", "Country") values (491, 'Tarui', 'Japan');
insert into public."Location" ("Id", "City", "Country") values (492, 'Káto Asítai', 'Greece');
insert into public."Location" ("Id", "City", "Country") values (493, 'Saint-Tite', 'Canada');
insert into public."Location" ("Id", "City", "Country") values (494, 'Sudikampir', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (495, 'Jianqiao', 'China');
insert into public."Location" ("Id", "City", "Country") values (496, 'General Enrique Godoy', 'Argentina');
insert into public."Location" ("Id", "City", "Country") values (497, 'Amadeo', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (498, 'Mbocayaty', 'Paraguay');
insert into public."Location" ("Id", "City", "Country") values (499, 'Nyandoma', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (500, 'Longbo', 'China');
insert into public."Location" ("Id", "City", "Country") values (501, 'Zhujiaqiao', 'China');
insert into public."Location" ("Id", "City", "Country") values (502, 'Saint Catherine', 'Egypt');
insert into public."Location" ("Id", "City", "Country") values (503, 'Boa Viagem', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (504, 'Xihe', 'China');
insert into public."Location" ("Id", "City", "Country") values (505, 'Décines-Charpieu', 'France');
insert into public."Location" ("Id", "City", "Country") values (506, 'Goascorán', 'Honduras');
insert into public."Location" ("Id", "City", "Country") values (507, 'Ciengang', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (508, 'Agkathiá', 'Greece');
insert into public."Location" ("Id", "City", "Country") values (509, 'Haradok', 'Belarus');
insert into public."Location" ("Id", "City", "Country") values (510, 'Tajinan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (511, 'Kembangan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (512, 'Thành Phố Phủ Lý', 'Vietnam');
insert into public."Location" ("Id", "City", "Country") values (513, 'Fryanovo', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (514, 'Imus', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (515, 'Thị Trấn Mộc Châu', 'Vietnam');
insert into public."Location" ("Id", "City", "Country") values (516, 'Manuel Roxas', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (517, 'Parthenay', 'France');
insert into public."Location" ("Id", "City", "Country") values (518, 'Watthana Nakhon', 'Thailand');
insert into public."Location" ("Id", "City", "Country") values (519, 'Tubigan', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (520, 'Okrika', 'Nigeria');
insert into public."Location" ("Id", "City", "Country") values (521, 'Hecun', 'China');
insert into public."Location" ("Id", "City", "Country") values (522, 'Staritsa', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (523, 'Sarykemer', 'Kazakhstan');
insert into public."Location" ("Id", "City", "Country") values (524, 'Şirvan', 'Azerbaijan');
insert into public."Location" ("Id", "City", "Country") values (525, 'Idrinskoye', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (526, 'Jeżów', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (527, 'Savski Venac', 'Serbia');
insert into public."Location" ("Id", "City", "Country") values (528, 'Nancheng', 'China');
insert into public."Location" ("Id", "City", "Country") values (529, 'Lynchburg', 'United States');
insert into public."Location" ("Id", "City", "Country") values (530, 'Guanyinge', 'China');
insert into public."Location" ("Id", "City", "Country") values (531, 'Phultala', 'Bangladesh');
insert into public."Location" ("Id", "City", "Country") values (532, 'Parawan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (533, 'Shangtian', 'China');
insert into public."Location" ("Id", "City", "Country") values (534, 'Milevsko', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (535, 'Czarków', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (536, 'Noşratābād', 'Iran');
insert into public."Location" ("Id", "City", "Country") values (537, 'Mandōl', 'Afghanistan');
insert into public."Location" ("Id", "City", "Country") values (538, 'Foxrock', 'Ireland');
insert into public."Location" ("Id", "City", "Country") values (539, 'Stockholm', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (540, 'Changsheng', 'China');
insert into public."Location" ("Id", "City", "Country") values (541, 'Danilov', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (542, 'Chimtāl', 'Afghanistan');
insert into public."Location" ("Id", "City", "Country") values (543, 'Librazhd', 'Albania');
insert into public."Location" ("Id", "City", "Country") values (544, 'Acas', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (545, 'Tabinay', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (546, 'Wyszki', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (547, 'Neresnytsya', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (548, 'Taubaté', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (549, 'Phu Kam Yao', 'Thailand');
insert into public."Location" ("Id", "City", "Country") values (550, 'Lamadelaine', 'Luxembourg');
insert into public."Location" ("Id", "City", "Country") values (551, 'Nacka', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (552, 'Rasony', 'Belarus');
insert into public."Location" ("Id", "City", "Country") values (553, 'Nastola', 'Finland');
insert into public."Location" ("Id", "City", "Country") values (554, 'Waikambila', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (555, 'Alburitel', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (556, 'Zaandam', 'Netherlands');
insert into public."Location" ("Id", "City", "Country") values (557, 'Sakurai', 'Japan');
insert into public."Location" ("Id", "City", "Country") values (558, 'Nanjing', 'China');
insert into public."Location" ("Id", "City", "Country") values (559, 'Xiangxi', 'China');
insert into public."Location" ("Id", "City", "Country") values (560, 'Yuzhai', 'China');
insert into public."Location" ("Id", "City", "Country") values (561, 'Chaloem Phra Kiat', 'Thailand');
insert into public."Location" ("Id", "City", "Country") values (562, 'Yashan', 'China');
insert into public."Location" ("Id", "City", "Country") values (563, 'Tuchengzi', 'China');
insert into public."Location" ("Id", "City", "Country") values (564, 'Sorinomo', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (565, 'Lamawan', 'China');
insert into public."Location" ("Id", "City", "Country") values (566, 'Lishui', 'China');
insert into public."Location" ("Id", "City", "Country") values (567, 'Jinxiang', 'China');
insert into public."Location" ("Id", "City", "Country") values (568, 'Pangalangan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (569, 'Luozhou', 'China');
insert into public."Location" ("Id", "City", "Country") values (570, 'Paris 17', 'France');
insert into public."Location" ("Id", "City", "Country") values (571, 'Miches', 'Dominican Republic');
insert into public."Location" ("Id", "City", "Country") values (572, 'Kuching', 'Malaysia');
insert into public."Location" ("Id", "City", "Country") values (573, 'Пласница', 'Macedonia');
insert into public."Location" ("Id", "City", "Country") values (574, 'Manyana', 'Botswana');
insert into public."Location" ("Id", "City", "Country") values (575, 'Hoeryŏng', 'North Korea');
insert into public."Location" ("Id", "City", "Country") values (576, 'Teno', 'Chile');
insert into public."Location" ("Id", "City", "Country") values (577, 'Escazú', 'Costa Rica');
insert into public."Location" ("Id", "City", "Country") values (578, 'Serra D''El Rei', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (579, 'Jiayuguan', 'China');
insert into public."Location" ("Id", "City", "Country") values (580, 'Morant Bay', 'Jamaica');
insert into public."Location" ("Id", "City", "Country") values (581, 'Ferrol', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (582, 'Pskov', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (583, 'Syanno', 'Belarus');
insert into public."Location" ("Id", "City", "Country") values (584, 'Tunoshna', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (585, 'Sorol', 'Micronesia');
insert into public."Location" ("Id", "City", "Country") values (586, 'Vermoim', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (587, 'Gesik', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (588, 'Blois', 'France');
insert into public."Location" ("Id", "City", "Country") values (589, 'Cedar Rapids', 'United States');
insert into public."Location" ("Id", "City", "Country") values (590, 'Ḩawallī', 'Kuwait');
insert into public."Location" ("Id", "City", "Country") values (591, 'Dadian', 'China');
insert into public."Location" ("Id", "City", "Country") values (592, 'Serang', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (593, 'Taihe', 'China');
insert into public."Location" ("Id", "City", "Country") values (594, 'Bukovany', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (595, '‘Afula ‘Illit', 'Israel');
insert into public."Location" ("Id", "City", "Country") values (596, 'Penisihan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (597, 'Radashkovichy', 'Belarus');
insert into public."Location" ("Id", "City", "Country") values (598, 'Clermont-Ferrand', 'France');
insert into public."Location" ("Id", "City", "Country") values (599, 'Caledon', 'South Africa');
insert into public."Location" ("Id", "City", "Country") values (600, 'Ubrub', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (601, 'Yong’an', 'China');
insert into public."Location" ("Id", "City", "Country") values (602, 'La Hacienda', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (603, 'Yingkeng', 'China');
insert into public."Location" ("Id", "City", "Country") values (604, 'Kobylí', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (605, 'Gongju', 'South Korea');
insert into public."Location" ("Id", "City", "Country") values (606, 'Lagos', 'Nigeria');
insert into public."Location" ("Id", "City", "Country") values (607, 'Balayong', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (608, 'El Zapotal del Norte', 'Honduras');
insert into public."Location" ("Id", "City", "Country") values (609, 'Shuangyang', 'China');
insert into public."Location" ("Id", "City", "Country") values (610, 'Kolobovo', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (611, 'Kafr ash Shaykh', 'Egypt');
insert into public."Location" ("Id", "City", "Country") values (612, 'Vnorovy', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (613, 'Pousada', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (614, 'Armash', 'Armenia');
insert into public."Location" ("Id", "City", "Country") values (615, 'Sil-li', 'North Korea');
insert into public."Location" ("Id", "City", "Country") values (616, 'Shuangxiqiao', 'China');
insert into public."Location" ("Id", "City", "Country") values (617, 'Comodoro Rivadavia', 'Argentina');
insert into public."Location" ("Id", "City", "Country") values (618, 'Sātkania', 'Bangladesh');
insert into public."Location" ("Id", "City", "Country") values (619, 'Alhambra', 'United States');
insert into public."Location" ("Id", "City", "Country") values (620, 'Vila Verde', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (621, 'Kungshamn', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (622, 'Mahikeng', 'South Africa');
insert into public."Location" ("Id", "City", "Country") values (623, 'Viradouro', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (624, 'Šentilj v Slov. Goricah', 'Slovenia');
insert into public."Location" ("Id", "City", "Country") values (625, 'Melgar', 'Colombia');
insert into public."Location" ("Id", "City", "Country") values (626, 'Maodao', 'China');
insert into public."Location" ("Id", "City", "Country") values (627, 'Luoyang', 'China');
insert into public."Location" ("Id", "City", "Country") values (628, 'Karátoulas', 'Greece');
insert into public."Location" ("Id", "City", "Country") values (629, 'Lingshan', 'China');
insert into public."Location" ("Id", "City", "Country") values (630, 'Lapa', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (631, 'Potęgowo', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (632, 'Katyr-Yurt', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (633, 'Guadalupe', 'Mexico');
insert into public."Location" ("Id", "City", "Country") values (634, 'Maszkienice', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (635, 'Karobokan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (636, 'Kongsvinger', 'Norway');
insert into public."Location" ("Id", "City", "Country") values (637, 'Olenegorsk', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (638, 'Jiyang', 'China');
insert into public."Location" ("Id", "City", "Country") values (639, 'Pittsburgh', 'United States');
insert into public."Location" ("Id", "City", "Country") values (640, 'Midlands', 'Mauritius');
insert into public."Location" ("Id", "City", "Country") values (641, 'Pengembur Dua', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (642, 'Zhuyang', 'China');
insert into public."Location" ("Id", "City", "Country") values (643, 'Sovetskoye', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (644, 'Nishor', 'Kosovo');
insert into public."Location" ("Id", "City", "Country") values (645, 'Klášterec nad Ohří', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (646, 'Yanglin', 'China');
insert into public."Location" ("Id", "City", "Country") values (647, 'Stockholm', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (648, 'La Guacamaya', 'Honduras');
insert into public."Location" ("Id", "City", "Country") values (649, 'Bamenda', 'Cameroon');
insert into public."Location" ("Id", "City", "Country") values (650, 'Tours', 'France');
insert into public."Location" ("Id", "City", "Country") values (651, 'Leloboko', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (652, 'Aihua', 'China');
insert into public."Location" ("Id", "City", "Country") values (653, 'Leran Wetan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (654, 'Chengzhai', 'China');
insert into public."Location" ("Id", "City", "Country") values (655, 'Somba', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (656, 'Kadujajar', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (657, 'Xiangqiao', 'China');
insert into public."Location" ("Id", "City", "Country") values (658, 'Facatativá', 'Colombia');
insert into public."Location" ("Id", "City", "Country") values (659, 'Huyunxiang', 'China');
insert into public."Location" ("Id", "City", "Country") values (660, 'Xinxiang', 'China');
insert into public."Location" ("Id", "City", "Country") values (661, 'Santiago de María', 'El Salvador');
insert into public."Location" ("Id", "City", "Country") values (662, 'Venta', 'Lithuania');
insert into public."Location" ("Id", "City", "Country") values (663, 'Marco', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (664, 'Nyuksenitsa', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (665, 'Nglego', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (666, '''Ali Sabieh', 'Djibouti');
insert into public."Location" ("Id", "City", "Country") values (667, 'Mrongi Daja', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (668, 'Bagombong', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (669, 'Ipuh', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (670, 'Da’an', 'China');
insert into public."Location" ("Id", "City", "Country") values (671, 'Strzelce', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (672, 'Caloue', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (673, 'Pīshvā', 'Iran');
insert into public."Location" ("Id", "City", "Country") values (674, 'Göteborg', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (675, 'Denver', 'United States');
insert into public."Location" ("Id", "City", "Country") values (676, 'Dargaz', 'Iran');
insert into public."Location" ("Id", "City", "Country") values (677, 'Akademija (Kaunas)', 'Lithuania');
insert into public."Location" ("Id", "City", "Country") values (678, 'Xixiang', 'China');
insert into public."Location" ("Id", "City", "Country") values (679, 'Cukanguncal', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (680, 'Châu Thành', 'Vietnam');
insert into public."Location" ("Id", "City", "Country") values (681, 'Capitão Poço', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (682, 'Xiadahe', 'China');
insert into public."Location" ("Id", "City", "Country") values (683, 'Las Junturas', 'Argentina');
insert into public."Location" ("Id", "City", "Country") values (684, 'Wyszki', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (685, 'Kurmanayevka', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (686, 'Sandefjord', 'Norway');
insert into public."Location" ("Id", "City", "Country") values (687, 'Santa Maria da Vitória', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (688, 'Gaotan', 'China');
insert into public."Location" ("Id", "City", "Country") values (689, 'Toledo', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (690, 'Tuguanpu', 'China');
insert into public."Location" ("Id", "City", "Country") values (691, 'Tor', 'Egypt');
insert into public."Location" ("Id", "City", "Country") values (692, 'Terjan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (693, 'Pedreira', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (694, 'Bazha', 'China');
insert into public."Location" ("Id", "City", "Country") values (695, 'Akhmīm', 'Egypt');
insert into public."Location" ("Id", "City", "Country") values (696, 'Paraty', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (697, 'Phoenix', 'United States');
insert into public."Location" ("Id", "City", "Country") values (698, 'Ngala', 'Nigeria');
insert into public."Location" ("Id", "City", "Country") values (699, 'Glondong', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (700, 'Pushkinskiye Gory', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (701, 'Aragarças', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (702, 'Krasnogorskiy', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (703, 'Göteborg', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (704, 'Chugay', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (705, 'Nagrog', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (706, 'Cikijing', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (707, 'Cambanay', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (708, 'Lhuentse', 'Bhutan');
insert into public."Location" ("Id", "City", "Country") values (709, 'Dahao', 'China');
insert into public."Location" ("Id", "City", "Country") values (710, 'Powidz', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (711, 'Bagumbayan', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (712, 'Shiyaogou', 'China');
insert into public."Location" ("Id", "City", "Country") values (713, 'Santa Catalina', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (714, 'Olympia', 'United States');
insert into public."Location" ("Id", "City", "Country") values (715, 'Dananshan', 'China');
insert into public."Location" ("Id", "City", "Country") values (716, 'Eksjö', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (717, 'Xiang Ngeun', 'Laos');
insert into public."Location" ("Id", "City", "Country") values (718, 'Hekou', 'China');
insert into public."Location" ("Id", "City", "Country") values (719, 'Karlstad', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (720, 'Kraslice', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (721, 'Boca Chica', 'Dominican Republic');
insert into public."Location" ("Id", "City", "Country") values (722, 'Bobigny', 'France');
insert into public."Location" ("Id", "City", "Country") values (723, 'Kizema', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (724, 'Franceville', 'Gabon');
insert into public."Location" ("Id", "City", "Country") values (725, 'San Antonio', 'Mexico');
insert into public."Location" ("Id", "City", "Country") values (726, 'Yasynuvata', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (727, 'Podu', 'China');
insert into public."Location" ("Id", "City", "Country") values (728, 'São Bento', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (729, 'Malārd', 'Iran');
insert into public."Location" ("Id", "City", "Country") values (730, 'Ordzhonikidze', 'Kazakhstan');
insert into public."Location" ("Id", "City", "Country") values (731, 'Budapest', 'Hungary');
insert into public."Location" ("Id", "City", "Country") values (732, 'Dasheng', 'China');
insert into public."Location" ("Id", "City", "Country") values (733, 'Pandan', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (734, 'Washington', 'United States');
insert into public."Location" ("Id", "City", "Country") values (735, 'Qili', 'China');
insert into public."Location" ("Id", "City", "Country") values (736, 'Stylída', 'Greece');
insert into public."Location" ("Id", "City", "Country") values (737, 'Ciguha Tengah', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (738, 'Suvorov', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (739, 'Fontainebleau', 'France');
insert into public."Location" ("Id", "City", "Country") values (740, 'Santa Rita', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (741, 'Grzybowa Góra', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (742, 'Lianrao', 'China');
insert into public."Location" ("Id", "City", "Country") values (743, 'Siheyuan', 'China');
insert into public."Location" ("Id", "City", "Country") values (744, 'Sumberkindagan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (745, 'San Andrés Xecul', 'Guatemala');
insert into public."Location" ("Id", "City", "Country") values (746, 'Cournon-d''Auvergne', 'France');
insert into public."Location" ("Id", "City", "Country") values (747, 'Ḩarf al Musaytirah', 'Syria');
insert into public."Location" ("Id", "City", "Country") values (748, 'Sizhou', 'China');
insert into public."Location" ("Id", "City", "Country") values (749, 'Oguta', 'Nigeria');
insert into public."Location" ("Id", "City", "Country") values (750, 'Vishnyakovskiye Dachi', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (751, 'Dongfanghong', 'China');
insert into public."Location" ("Id", "City", "Country") values (752, 'Qingfenglin', 'China');
insert into public."Location" ("Id", "City", "Country") values (753, 'Tangjia', 'China');
insert into public."Location" ("Id", "City", "Country") values (754, 'Mangarine', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (755, 'Aksu', 'Kazakhstan');
insert into public."Location" ("Id", "City", "Country") values (756, 'Musawa', 'Nigeria');
insert into public."Location" ("Id", "City", "Country") values (757, 'Plyeshchanitsy', 'Belarus');
insert into public."Location" ("Id", "City", "Country") values (758, 'Tieshan', 'China');
insert into public."Location" ("Id", "City", "Country") values (759, 'Cibolek Kidul', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (760, 'Zigong', 'China');
insert into public."Location" ("Id", "City", "Country") values (761, 'Ferraria', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (762, 'Tignapalan', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (763, 'Trąbki Wielkie', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (764, 'Taiyangling', 'China');
insert into public."Location" ("Id", "City", "Country") values (765, 'Synevyr', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (766, 'Palotina', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (767, 'Olovyannaya', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (768, 'Shums’k', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (769, 'Mayenne', 'France');
insert into public."Location" ("Id", "City", "Country") values (770, 'Zhangzhu', 'China');
insert into public."Location" ("Id", "City", "Country") values (771, 'Igcocolo', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (772, 'Zhinvali', 'Georgia');
insert into public."Location" ("Id", "City", "Country") values (773, 'Cibunar', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (774, 'Yejia', 'China');
insert into public."Location" ("Id", "City", "Country") values (775, 'Oju', 'Nigeria');
insert into public."Location" ("Id", "City", "Country") values (776, 'Santiago de María', 'El Salvador');
insert into public."Location" ("Id", "City", "Country") values (777, 'Janiuay', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (778, 'Krajan Karanganyar', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (779, 'Gandra', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (780, 'Grenoble', 'France');
insert into public."Location" ("Id", "City", "Country") values (781, 'Cingambul', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (782, 'Guane', 'Cuba');
insert into public."Location" ("Id", "City", "Country") values (783, 'Andarapa', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (784, 'Chitungwiza', 'Zimbabwe');
insert into public."Location" ("Id", "City", "Country") values (785, 'Pasirdalem', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (786, 'Bondokodi', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (787, 'Sakharovo', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (788, 'Bissen', 'Luxembourg');
insert into public."Location" ("Id", "City", "Country") values (789, 'Laranjeiras do Sul', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (790, 'Xiayang', 'China');
insert into public."Location" ("Id", "City", "Country") values (791, '‘Awaj', 'Syria');
insert into public."Location" ("Id", "City", "Country") values (792, 'Flandes', 'Colombia');
insert into public."Location" ("Id", "City", "Country") values (793, 'Toki', 'Japan');
insert into public."Location" ("Id", "City", "Country") values (794, 'Arroyito', 'Argentina');
insert into public."Location" ("Id", "City", "Country") values (795, 'Yulin', 'China');
insert into public."Location" ("Id", "City", "Country") values (796, 'Mesiméri', 'Greece');
insert into public."Location" ("Id", "City", "Country") values (797, 'Bamut', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (798, 'Novopokrovka', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (799, 'Lisboa', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (800, 'Longyearbyen', 'Svalbard and Jan Mayen');
insert into public."Location" ("Id", "City", "Country") values (801, 'Huata', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (802, 'Kalajoki', 'Finland');
insert into public."Location" ("Id", "City", "Country") values (803, 'Stockholm', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (804, 'Gunungpeundeuy', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (805, 'Amgalang', 'China');
insert into public."Location" ("Id", "City", "Country") values (806, 'Boyany', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (807, 'Krajenka', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (808, 'Guangdu', 'China');
insert into public."Location" ("Id", "City", "Country") values (809, 'Moret-sur-Loing', 'France');
insert into public."Location" ("Id", "City", "Country") values (810, 'Năm Căn', 'Vietnam');
insert into public."Location" ("Id", "City", "Country") values (811, 'Hokor', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (812, 'Arıqıran', 'Azerbaijan');
insert into public."Location" ("Id", "City", "Country") values (813, 'Miribel', 'France');
insert into public."Location" ("Id", "City", "Country") values (814, 'Pyatovskiy', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (815, 'Toulon', 'France');
insert into public."Location" ("Id", "City", "Country") values (816, 'Parion', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (817, 'Biankouma', 'Ivory Coast');
insert into public."Location" ("Id", "City", "Country") values (818, 'Tvøroyri', 'Faroe Islands');
insert into public."Location" ("Id", "City", "Country") values (819, 'La Loma', 'Mexico');
insert into public."Location" ("Id", "City", "Country") values (820, 'Portariá', 'Greece');
insert into public."Location" ("Id", "City", "Country") values (821, 'Touho', 'New Caledonia');
insert into public."Location" ("Id", "City", "Country") values (822, 'Al Ḩāḑir', 'Syria');
insert into public."Location" ("Id", "City", "Country") values (823, 'Mtubatuba', 'South Africa');
insert into public."Location" ("Id", "City", "Country") values (824, 'Ōdachō-ōda', 'Japan');
insert into public."Location" ("Id", "City", "Country") values (825, 'Liugou', 'China');
insert into public."Location" ("Id", "City", "Country") values (826, 'Poroçan', 'Albania');
insert into public."Location" ("Id", "City", "Country") values (827, 'Tadjoura', 'Djibouti');
insert into public."Location" ("Id", "City", "Country") values (828, 'Dongba', 'China');
insert into public."Location" ("Id", "City", "Country") values (829, 'Neuilly-sur-Marne', 'France');
insert into public."Location" ("Id", "City", "Country") values (830, 'Tomohon', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (831, 'Fengtai Chengguanzhen', 'China');
insert into public."Location" ("Id", "City", "Country") values (832, 'Arroio Grande', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (833, 'Simnas', 'Lithuania');
insert into public."Location" ("Id", "City", "Country") values (834, 'Ikalamavony', 'Madagascar');
insert into public."Location" ("Id", "City", "Country") values (835, 'Zouérat', 'Mauritania');
insert into public."Location" ("Id", "City", "Country") values (836, 'Itzer', 'Morocco');
insert into public."Location" ("Id", "City", "Country") values (837, 'Lamalewo', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (838, 'Independencia', 'Mexico');
insert into public."Location" ("Id", "City", "Country") values (839, 'Coromoro', 'Colombia');
insert into public."Location" ("Id", "City", "Country") values (840, 'Solidaridad', 'Mexico');
insert into public."Location" ("Id", "City", "Country") values (841, 'Lynchburg', 'United States');
insert into public."Location" ("Id", "City", "Country") values (842, 'Cruz Alta', 'Argentina');
insert into public."Location" ("Id", "City", "Country") values (843, 'Néma', 'Mauritania');
insert into public."Location" ("Id", "City", "Country") values (844, 'Katyr-Yurt', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (845, 'Bafia', 'Cameroon');
insert into public."Location" ("Id", "City", "Country") values (846, 'Livadiya', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (847, 'Varjota', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (848, 'Magtaking', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (849, 'Peña Blanca', 'Honduras');
insert into public."Location" ("Id", "City", "Country") values (850, 'Tongzi', 'China');
insert into public."Location" ("Id", "City", "Country") values (851, 'Frampol', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (852, 'Węgrzce Wielkie', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (853, 'Nirgua', 'Venezuela');
insert into public."Location" ("Id", "City", "Country") values (854, 'Balongmulyo', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (855, 'Dianzi', 'China');
insert into public."Location" ("Id", "City", "Country") values (856, 'Suzdal’', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (857, 'Mirovice', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (858, 'Baoyang', 'China');
insert into public."Location" ("Id", "City", "Country") values (859, 'København', 'Denmark');
insert into public."Location" ("Id", "City", "Country") values (860, 'Seaton', 'United Kingdom');
insert into public."Location" ("Id", "City", "Country") values (861, 'Niechanowo', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (862, 'Srabah', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (863, 'Alenquer', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (864, 'Maracás', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (865, 'Longtou’an', 'China');
insert into public."Location" ("Id", "City", "Country") values (866, 'Quintãs', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (867, 'Dū Laīnah', 'Afghanistan');
insert into public."Location" ("Id", "City", "Country") values (868, 'Grigoropolisskaya', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (869, 'Derventa', 'Bosnia and Herzegovina');
insert into public."Location" ("Id", "City", "Country") values (870, 'Dongpu', 'China');
insert into public."Location" ("Id", "City", "Country") values (871, 'Ypacarai', 'Paraguay');
insert into public."Location" ("Id", "City", "Country") values (872, 'Minuwangoda', 'Sri Lanka');
insert into public."Location" ("Id", "City", "Country") values (873, 'Basar', 'China');
insert into public."Location" ("Id", "City", "Country") values (874, 'Mpigi', 'Uganda');
insert into public."Location" ("Id", "City", "Country") values (875, 'Pakemitan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (876, 'Ashley', 'United Kingdom');
insert into public."Location" ("Id", "City", "Country") values (877, 'Kawanoechō', 'Japan');
insert into public."Location" ("Id", "City", "Country") values (878, 'Regla', 'Cuba');
insert into public."Location" ("Id", "City", "Country") values (879, 'Zimmi', 'Sierra Leone');
insert into public."Location" ("Id", "City", "Country") values (880, 'Banjar Sembunggede', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (881, 'Skýros', 'Greece');
insert into public."Location" ("Id", "City", "Country") values (882, 'Marādah', 'Libya');
insert into public."Location" ("Id", "City", "Country") values (883, 'Horlivka', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (884, 'Chenjiaba', 'China');
insert into public."Location" ("Id", "City", "Country") values (885, 'Navashino', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (886, 'Petaling Jaya', 'Malaysia');
insert into public."Location" ("Id", "City", "Country") values (887, 'Riofrío', 'Colombia');
insert into public."Location" ("Id", "City", "Country") values (888, 'Fāqūs', 'Egypt');
insert into public."Location" ("Id", "City", "Country") values (889, 'Angoulême', 'France');
insert into public."Location" ("Id", "City", "Country") values (890, 'Paramaribo', 'Suriname');
insert into public."Location" ("Id", "City", "Country") values (891, 'Dzikowiec', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (892, 'Jinghong', 'China');
insert into public."Location" ("Id", "City", "Country") values (893, 'Lubbock', 'United States');
insert into public."Location" ("Id", "City", "Country") values (894, 'Gora', 'Nigeria');
insert into public."Location" ("Id", "City", "Country") values (895, 'Ocoyo', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (896, 'Solo', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (897, 'Gambarjati', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (898, 'Nijmegen', 'Netherlands');
insert into public."Location" ("Id", "City", "Country") values (899, 'Rio Covo', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (900, 'Roscoff', 'France');
insert into public."Location" ("Id", "City", "Country") values (901, 'Indianapolis', 'United States');
insert into public."Location" ("Id", "City", "Country") values (902, 'Chengui', 'China');
insert into public."Location" ("Id", "City", "Country") values (903, 'Mandala', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (904, 'Fenggao', 'China');
insert into public."Location" ("Id", "City", "Country") values (905, 'Gaula', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (906, 'Doghs', 'Armenia');
insert into public."Location" ("Id", "City", "Country") values (907, 'Sempu', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (908, 'Baozi', 'China');
insert into public."Location" ("Id", "City", "Country") values (909, 'Topeka', 'United States');
insert into public."Location" ("Id", "City", "Country") values (910, 'Sam Chuk', 'Thailand');
insert into public."Location" ("Id", "City", "Country") values (911, 'Birigui', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (912, 'Mocupe', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (913, 'Le Mans', 'France');
insert into public."Location" ("Id", "City", "Country") values (914, 'Taen Tengah', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (915, 'Kampong Chhnang', 'Cambodia');
insert into public."Location" ("Id", "City", "Country") values (916, 'Song’ao', 'China');
insert into public."Location" ("Id", "City", "Country") values (917, 'Pagedangan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (918, 'Xilian', 'China');
insert into public."Location" ("Id", "City", "Country") values (919, 'Huanggexi', 'China');
insert into public."Location" ("Id", "City", "Country") values (920, 'Shiyan', 'China');
insert into public."Location" ("Id", "City", "Country") values (921, 'Milot', 'Haiti');
insert into public."Location" ("Id", "City", "Country") values (922, 'Ciasna', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (923, 'Bileća', 'Bosnia and Herzegovina');
insert into public."Location" ("Id", "City", "Country") values (924, 'Neskaupstaður', 'Iceland');
insert into public."Location" ("Id", "City", "Country") values (925, 'Konārak', 'Iran');
insert into public."Location" ("Id", "City", "Country") values (926, 'Port Elizabeth', 'Saint Vincent and the Grenadines');
insert into public."Location" ("Id", "City", "Country") values (927, 'Garibaldi', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (928, 'Sabana Grande de Palenque', 'Dominican Republic');
insert into public."Location" ("Id", "City", "Country") values (929, 'Port-au-Prince', 'Haiti');
insert into public."Location" ("Id", "City", "Country") values (930, 'Ulan Hua', 'China');
insert into public."Location" ("Id", "City", "Country") values (931, 'Laoqiao', 'China');
insert into public."Location" ("Id", "City", "Country") values (932, 'Tangwāni', 'Pakistan');
insert into public."Location" ("Id", "City", "Country") values (933, 'Ust’-Ulagan', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (934, 'Benito Juarez', 'Mexico');
insert into public."Location" ("Id", "City", "Country") values (935, 'Sofo-Birnin-Gwari', 'Nigeria');
insert into public."Location" ("Id", "City", "Country") values (936, 'Guangpu', 'China');
insert into public."Location" ("Id", "City", "Country") values (937, 'New Washington', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (938, 'Jianchang', 'China');
insert into public."Location" ("Id", "City", "Country") values (939, 'Tögrög', 'Mongolia');
insert into public."Location" ("Id", "City", "Country") values (940, 'Brest', 'France');
insert into public."Location" ("Id", "City", "Country") values (941, 'Sarapul', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (942, 'El Puente', 'Honduras');
insert into public."Location" ("Id", "City", "Country") values (943, 'Khlong Sam Wa', 'Thailand');
insert into public."Location" ("Id", "City", "Country") values (944, 'Riđica', 'Serbia');
insert into public."Location" ("Id", "City", "Country") values (945, 'Dhahab', 'Egypt');
insert into public."Location" ("Id", "City", "Country") values (946, 'Novosil’', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (947, 'Morropón', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (948, 'Isdalstø', 'Norway');
insert into public."Location" ("Id", "City", "Country") values (949, 'Bamusso', 'Cameroon');
insert into public."Location" ("Id", "City", "Country") values (950, 'Horta', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (951, 'Sakura', 'Japan');
insert into public."Location" ("Id", "City", "Country") values (952, 'Sidi Bousber', 'Morocco');
insert into public."Location" ("Id", "City", "Country") values (953, 'Jianqiao', 'China');
insert into public."Location" ("Id", "City", "Country") values (954, 'Batumi', 'Georgia');
insert into public."Location" ("Id", "City", "Country") values (955, 'Itanhandu', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (956, 'Kvissleby', 'Sweden');
insert into public."Location" ("Id", "City", "Country") values (957, 'Yangjingziwan', 'China');
insert into public."Location" ("Id", "City", "Country") values (958, 'Langkapcaang Hilir', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (959, 'Samobor', 'Croatia');
insert into public."Location" ("Id", "City", "Country") values (960, 'Heydərabad', 'Azerbaijan');
insert into public."Location" ("Id", "City", "Country") values (961, 'Jiaomingsi', 'China');
insert into public."Location" ("Id", "City", "Country") values (962, 'Radzyń Chełmiński', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (963, 'Yepocapa', 'Guatemala');
insert into public."Location" ("Id", "City", "Country") values (964, 'Parrita', 'Costa Rica');
insert into public."Location" ("Id", "City", "Country") values (965, 'Nova Venécia', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (966, 'Trois-Rivières', 'Canada');
insert into public."Location" ("Id", "City", "Country") values (967, 'Patapan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (968, 'Blinsung', 'Philippines');
insert into public."Location" ("Id", "City", "Country") values (969, 'Kimitsu', 'Japan');
insert into public."Location" ("Id", "City", "Country") values (970, 'Mường Nhé', 'Vietnam');
insert into public."Location" ("Id", "City", "Country") values (971, 'Notsé', 'Togo');
insert into public."Location" ("Id", "City", "Country") values (972, 'Zhovti Vody', 'Ukraine');
insert into public."Location" ("Id", "City", "Country") values (973, 'Ronov nad Doubravou', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (974, 'Gomunice', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (975, 'Poříčany', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (976, 'Gremyachinsk', 'Russia');
insert into public."Location" ("Id", "City", "Country") values (977, 'Zala', 'China');
insert into public."Location" ("Id", "City", "Country") values (978, 'Brest', 'France');
insert into public."Location" ("Id", "City", "Country") values (979, 'Pedro Leopoldo', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (980, 'Kwangju', 'South Korea');
insert into public."Location" ("Id", "City", "Country") values (981, 'Wuluhan', 'Indonesia');
insert into public."Location" ("Id", "City", "Country") values (982, 'Předměřice nad Labem', 'Czech Republic');
insert into public."Location" ("Id", "City", "Country") values (983, 'Auki', 'Solomon Islands');
insert into public."Location" ("Id", "City", "Country") values (984, 'An Naşşārīyah', 'Palestinian Territory');
insert into public."Location" ("Id", "City", "Country") values (985, 'Dayushu', 'China');
insert into public."Location" ("Id", "City", "Country") values (986, 'Naivasha', 'Kenya');
insert into public."Location" ("Id", "City", "Country") values (987, 'Zhenziliang', 'China');
insert into public."Location" ("Id", "City", "Country") values (988, 'San Javier', 'Uruguay');
insert into public."Location" ("Id", "City", "Country") values (989, 'El Progreso', 'Panama');
insert into public."Location" ("Id", "City", "Country") values (990, 'Villamaría', 'Colombia');
insert into public."Location" ("Id", "City", "Country") values (991, 'Gongxi', 'China');
insert into public."Location" ("Id", "City", "Country") values (992, 'Vila Nova', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (993, 'Korczew', 'Poland');
insert into public."Location" ("Id", "City", "Country") values (994, 'Gio Linh', 'Vietnam');
insert into public."Location" ("Id", "City", "Country") values (995, 'Orleans', 'Brazil');
insert into public."Location" ("Id", "City", "Country") values (996, 'Soissons', 'France');
insert into public."Location" ("Id", "City", "Country") values (997, 'Silveiros', 'Portugal');
insert into public."Location" ("Id", "City", "Country") values (998, 'Coasa', 'Peru');
insert into public."Location" ("Id", "City", "Country") values (999, 'Dallas', 'United States');
insert into public."Location" ("Id", "City", "Country") values (1000, 'Rungis', 'France');
